name: Create and publish a Docker image

# Configures this workflow to run every time a version tag is pushed or a PR is opened.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestations and cache entries with GitHub OIDC
      packages: write # For pushing to ghcr.io
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}
